- name: Remove symlink
  file: path="{{ app_current_location }}" state=absent
- name: Update symlink
  file: src="{{ app_packages_dir }}/{{ app_version }}" dest="{{ app_current_location }}" state=link
